version: "3"
services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "passthis"
      MYSQL_DATABASE: "gamespace"
      MYSQL_USER: "wolfplus"
      MYSQL_PASSWORD: "passthis"
    volumes:
    - my-datavolume:/var/lib/mysql
  
  app:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    links:
      - mysql
    ports:
      - 8080:80
    volumes:
      - /sessions

volumes:
  my-datavolume: