# Mysql server config
[database]
# connect = "wolfplus:4Dd878f1!@tcp(64.64.226.58:3306)/gamespace"
# connect = "wolfplus:4Dd878f1?@tcp(74.120.175.235:3306)/gamespace"
connect = "wolfplus:4Dd878f1!@tcp(127.0.0.1:3306)/gamespace"
max_idle_conns = 20
max_open_conns = 15
show_sql = true

#WEB服务器设置
[webserver]
#addr = "0.0.0.0"
addr = "144.34.172.115"
port = ":8080"                         #监听地址
enable_ssl = false                            #是否使用https, 如果为true, 则必须配置cert和key的路径
static_dir = "web/static"
