version: "3"
services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "passthis"
      MYSQL_DATABASE: "gamespace"
      MYSQL_USER: "wolfplus"
      MYSQL_PASSWORD: "passthis"
    volumes:
    - F:/Mount/mysql:/var/lib/mysql