[core]
# enable debug mode
debug = false
heartbeat = 30

[game-server]
host = "127.0.0.1"
port = 12308

#WEB服务器设置
[webserver]
addr = "0.0.0.0:12308"                         #监听地址
enable_ssl = false                            #是否使用https, 如果为true, 则必须配置cert和key的路径
static_dir = "web/static"

[webserver.certificates]
cert = "configs/****.crt"       #证书路径
key = "configs/****.key"        #Key路径

# Mysql server config
[database]
connect = "wolfplus:4Dd878f1!@tcp(127.0.0.1:3306)/gamespace"
# connect = "wolfplus:passthis@tcp(18.224.110.0:3306)/gamespace"
# connect = "wolfplus:4Dd878f1?@tcp(74.120.175.235:3306)/gamespace"
max_idle_conns = 20
max_open_conns = 15
show_sql = true

#Token设置
[token]
expires = 21600                        #token过期时间
